### ISSUE TITLE
Bug: Cannot find name 'Marker'

### ISSUE THREAD

**Issue by rbalet** [googlemaps/js-markerclusterer#644]
#### Environment details

2. OS type and version: MacOS Ventura 13.3.1
3. Library version and other environment information : 2.1.3

#### Steps to reproduce

  1. `npm i @googlemaps/markerclusterer@latest`

#### Stack trace
```
node_modules/@googlemaps/markerclusterer/dist/markerclusterer.d.ts:64:25 - error TS2304: Cannot find name 'Marker'.

64     addMarkers(markers: Marker[], noDraw?: boolean): void;
                           ~~~~~~
node_modules/@googlemaps/markerclusterer/dist/markerclusterer.d.ts:65:26 - error TS2304: Cannot find name 'Marker'.

65     removeMarker(marker: Marker, noDraw?: boolean): boolean;
                            ~~~~~~
node_modules/@googlemaps/markerclusterer/dist/markerclusterer.d.ts:66:28 - error TS2304: Cannot find name 'Marker'.

66     removeMarkers(markers: Marker[], noDraw?: boolean): boolean;
```

#### Additional
It was working on the v2.0.15

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react with :+1: so we can see what is popular when we triage.
--------

@rbalet Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._
